function [IDs,valid] = selectCameras(hd,SelectionMode)
    listCams = {hd.Cameras.Name} ;
    [IDs,valid] = listdlg('PromptString','Select Cameras :',...
                                'SelectionMode',SelectionMode,...
                                'initialValue',1,...
                                'ListString',listCams) ;
end