function navDIC_startup
%% DEFINE DEFAULT GRAPHIC BEHAVIOR
    fontUnits = 'points' ;
    fontSize = 18 ;
    fontName = 'consolas' ;
    fontInterpreter = 'latex' ;
    set(0 ...
        ... FIGURES
            ,'DefaultFigureColor', 'w' ...
            ...,'DefaultFigureWindowStyle', 'docked' ...
            ...,'DefaultFigurePaperType', 'A4' ...
            ,'DefaultFigurePaperPositionMode', 'auto' ...
            ,'DefaultFigureCreateFcn',@(fig,~)addToolbarExplorationButtons(fig) ...
            ,'DefaultFigureColormap',jet(1000) ...
        ... AXES
            ,'DefaultAxesToolbarVisible','off' ...
            ,'DefaultAxesInteractions',[panInteraction zoomInteraction] ...
            ,'DefaultAxesBox','on' ...
            ,'DefaultAxesBoxStyle','Full' ...
            ,'DefaultAxesColor', 'none' ...
            ,'DefaultAxesLooseInset',[2 1 1 1]*0.04 ...
            ...,'DefaultAxesDrawMode', 'fast' ...
            ... Text font
            ,'DefaultAxesFontUnits', fontUnits ...
            ,'DefaultAxesFontSize', fontSize ...
            ,'DefaultAxesFontName', fontName ...
            ,'DefaultAxesTickLabelInterpreter', fontInterpreter ...
            ... Grid
            ,'DefaultAxesGridColor', [1 1 1]*0 ...
            ,'DefaultAxesGridAlpha', 0.2 ...
            ,'DefaultAxesGridLineStyle', '--' ...
            ,'DefaultAxesXGrid', 'on' ...
            ,'DefaultAxesYGrid', 'on' ...
            ,'DefaultAxesInterruptible', 'on' ...
            ,'DefaultAxesLayer', 'Top' ...
            ,'DefaultAxesNextPlot', 'add' ...
            ,'DefaultAxesUnits', 'normalized' ...
            ,'DefaultAxesXcolor', [0, 0, 0] ...
            ,'DefaultAxesYcolor', [0, 0, 0] ...
            ,'DefaultAxesZcolor', [0, 0, 0] ...
            ,'DefaultAxesVisible', 'on' ...
        ... LINES
            ...,'DefaultLineColor', 'Red' ...
            ,'DefaultLineLineStyle', '-' ...
            ,'DefaultLineLineWidth', 2 ...
            ,'DefaultLineMarker', 'none' ...
            ,'DefaultLineMarkerSize', 8 ...
        ... TEXT
            ,'DefaultTextColor', [0, 0, 0] ...
            ,'DefaultTextFontUnits', fontUnits ...
            ,'DefaultTextFontSize', fontSize ...
            ,'DefaultTextInterpreter', fontInterpreter ...
            ,'DefaultTextFontName', fontName ...
            ,'DefaultTextVerticalAlignment', 'middle' ...
            ,'DefaultTextHorizontalAlignment', 'center'...
        ... LEGENDS
            ,'DefaultLegendEdgeColor','k'...
            ...,'DefaultlegendLocation','NorthEast' ...
            ,'DefaultLegendFontUnits', fontUnits ...
            ,'DefaultLegendFontSize', fontSize ...
            ,'DefaultLegendInterpreter', fontInterpreter ...
            ,'DefaultLegendFontName', fontName ...
        ... COLORBARS
            ,'DefaultColorbarFontSize', fontSize ...
            ,'DefaultColorbarTickLabelInterpreter', fontInterpreter ...
            ,'DefaultColorbarFontName', fontName ...
    ) ;