global hd

IMG = hd.Images{1} ;
convFilt = @(I)conv2(I,ones(1),'same') ;
diffImg = @(ii)abs(convFilt(IMG(:,:,:,ii)-IMG(:,:,:,ii-1))) ;

clf
    im = imagesc(IMG(:,:,:,1)) ;
        axis ij
        axis equal
        axis tight
        set(gca,'xtick',[],'ytick',[])
    slider = uicontrol(gcf ...
                ,'style','slider' ...
                ,'Units','normalized' ...
                ,'position',[0 0 1 0.025] ...
                ,'min',2 ...
                ,'max',size(IMG,4) ...
                ,'SliderStep',[1/(size(IMG,4)-1) 1/10] ...
                ...,'callback',@(src,evt)set(im,'CData',diffImg(round(src.Value))) ...
                ) ;
    addlistener(slider,'Value','PostSet',@(src,evt)set(im,'CData',diffImg(round(slider.Value)))) ;
    slider.Value = 2 ;
    
    