%% SEND THE RESULT TO navDIC
        hd.Seeds(seedNumber).Strains = interpn(...
                                                repmat((1:size(Strains,1))',[1 3 nFrames]),...
                                                repmat(1:3,[size(Strains,1) 1 nFrames]),...
                                                repmat(reshape(frames,[1 1 nFrames]),[size(Strains,1) 3 1]),...
                                                Strains,...
                                                repmat((1:size(Strains,1))',[1 3 hd.nFrames]),...
                                                repmat(1:3,[size(Strains,1) 1 hd.nFrames]),...
                                                repmat(reshape(navDICFrames,[1 1 hd.nFrames]),[size(Strains,1) 3 1]),...
                                            'linear',NaN) ;
        hd.Seeds(seedNumber).MovingPoints = interpn(...
                                                repmat((1:nNodes)',[1 2 nFrames]),...
                                                repmat(1:2,[nNodes 1 nFrames]),...
                                                repmat(reshape(frames,[1 1 nFrames]),[nNodes 2 1]),...
                                                Xn,...
                                                repmat((1:nNodes)',[1 2 hd.nFrames]),...
                                                repmat(1:2,[nNodes 1 hd.nFrames]),...
                                                repmat(reshape(navDICFrames,[1 1 hd.nFrames]),[nNodes 2 1]),...
                                            'linear',NaN) ;
        hd.Seeds(seedNumber).Displacements = interpn(...
                                                repmat((1:nNodes)',[1 2 nFrames]),...
                                                repmat(1:2,[nNodes 1 nFrames]),...
                                                repmat(reshape(frames,[1 1 nFrames]),[nNodes 2 1]),...
                                                Un,...
                                                repmat((1:nNodes)',[1 2 hd.nFrames]),...
                                                repmat(1:2,[nNodes 1 hd.nFrames]),...
                                                repmat(reshape(navDICFrames,[1 1 hd.nFrames]),[nNodes 2 1]),...
                                            'linear',NaN) ;