clc
close all
%clear all

uiContextMenu = {'h0',num2cell(num2str(round((1.4).^(1:15)')),2),{'15'};...
                'h',num2cell(num2str(round((1.4).^(1:15)')),2),{'15'};...
                'l',num2cell(num2str(round((1.4).^(8:23)')),2),{'79'};...
                'CORRSIZEX',num2cell(num2str((5:40)'),2),{'10'};...
                'CORRSIZEY',num2cell(num2str((5:40)'),2),{'10'};...
                } ;

H = drawingTool('drawROI',true ...
                ,'uicontextmenu',uiContextMenu ...
                ,'updateCallback',@(H)navDIC_processShapesForDistMesh(H)...
                ) ;
            
%%

H = drawingTool(H) ;

%% ajout corrSize plus afficher fenetre de correlation
uiContextMenu = {'h0',num2cell(num2str(round((1.4).^(1:15)')),2),{'15'};...
                'h',num2cell(num2str(round((1.4).^(1:15)')),2),{'15'};...
                'l',num2cell(num2str(round((1.4).^(8:23)')),2),{'79'};...
                'CORRSIZEX',num2cell(num2str((5:40)'),2),{'10'};...
                'CORRSIZEY',num2cell(num2str((5:40)'),2),{'10'};...
                } ;

H = drawingTool('drawROI',true ...
                ,'uicontextmenu',uiContextMenu );

