clc
close all
%clear all

uiContextMenu = {'h0',num2cell(num2str(round((1.4).^(1:15)')),2),{'15'};...
                'h',num2cell(num2str(round((1.4).^(1:15)')),2),{'15'};...
                'l',num2cell(num2str(round((1.4).^(8:23)')),2),{'79'};...
                } ;

H = drawingTool('drawROI',true ...
                ,'uicontextmenu',uiContextMenu ...
                ,'updateCallback',@(H)navDIC_processShapesForDistMesh(H)...
                ) 
            
            
%%

H = drawingTool(H)