function [IDs,valid] = selectSeeds(hd,SelectionMode)
    listSeeds = {hd.Seeds.Name} ;
    [IDs,valid] = listdlg('PromptString','Select Seeds :',...
                                'SelectionMode',SelectionMode,...
                                'initialValue',1,...
                                'ListString',listSeeds) ;
end